spring:
  application:
    name: hexagonal

devdeolho:
  client:
    address:
      url: http://localhost:8082/address

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal